// Mocks generated by Mockito 5.2.0 from annotations
// in maryland_game_engine/test/data/stores/entity_attribute_value/flag/writable_flag_entity_attribute_value_store_test.dart.
// Do not manually edit this file.

import 'package:maryland_game_engine/data/primitives/entity_id.dart' as _i3;
import 'package:maryland_game_engine/data/stores/entity_attribute_value/flag/flag_entity_attribute_value_store.dart'
    as _i2;
import 'package:maryland_game_engine/data/stores/entity_attribute_value/flag/writable_flag_entity_attribute_value_store.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeFlagEntityAttributeValueStore_0 extends _i1.Fake
    implements _i2.FlagEntityAttributeValueStore {}

/// A class which mocks [FlagEntityAttributeValueStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlagEntityAttributeValueStore extends _i1.Mock
    implements _i2.FlagEntityAttributeValueStore {
  MockFlagEntityAttributeValueStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get(_i3.EntityId? entityId, int? attributeId) =>
      (super.noSuchMethod(Invocation.method(#get, [entityId, attributeId]),
          returnValue: false) as bool);
}

/// A class which mocks [WritableFlagEntityAttributeValueStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockWritableFlagEntityAttributeValueStore extends _i1.Mock
    implements _i4.WritableFlagEntityAttributeValueStore {
  MockWritableFlagEntityAttributeValueStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlagEntityAttributeValueStore get backingStore =>
      (super.noSuchMethod(Invocation.getter(#backingStore),
              returnValue: _FakeFlagEntityAttributeValueStore_0())
          as _i2.FlagEntityAttributeValueStore);
  @override
  bool get(_i3.EntityId? entityId, int? attributeId) =>
      (super.noSuchMethod(Invocation.method(#get, [entityId, attributeId]),
          returnValue: false) as bool);
  @override
  void set(_i3.EntityId? entityId, int? attributeId) =>
      super.noSuchMethod(Invocation.method(#set, [entityId, attributeId]),
          returnValueForMissingStub: null);
  @override
  void clear(_i3.EntityId? entityId, int? attributeId) =>
      super.noSuchMethod(Invocation.method(#clear, [entityId, attributeId]),
          returnValueForMissingStub: null);
  @override
  dynamic moveTo(_i4.WritableFlagEntityAttributeValueStore? store) =>
      super.noSuchMethod(Invocation.method(#moveTo, [store]));
}
