// Mocks generated by Mockito 5.2.0 from annotations
// in maryland_game_engine/test/data/stores/entity_attribute_value/writable_entity_attribute_value_store_test.dart.
// Do not manually edit this file.

import 'package:maryland_game_engine/data/primitives/entity_id.dart' as _i3;
import 'package:maryland_game_engine/data/stores/entity_attribute_value/entity_attribute_value_store.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [EntityAttributeValueStore].
///
/// See the documentation for Mockito's code generation for more information.
class EntityAttributeValueStoreMock extends _i1.Mock
    implements _i2.EntityAttributeValueStore<String?> {
  EntityAttributeValueStoreMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String? get(_i3.EntityId? entityId, int? attributeId) =>
      (super.noSuchMethod(Invocation.method(#get, [entityId, attributeId]))
          as String?);
}
