on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
    - run: flutter build linux
    - run: flutter build apk
    - run: flutter build appbundle
  windows:
    needs: ubuntu
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        architecture: x64
    - run: flutter pub get
    - run: flutter test
    - run: flutter build windows
  macos:
    needs: ubuntu
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        architecture: x64
    - run: flutter config --enable-macos-desktop
    - run: flutter pub get
    - run: flutter test
    - run: flutter build macos
    - run: flutter build ios --release --no-codesign
