on:
  push:
    branches:
      - '**'
  release:
    types: published
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
    - run: flutter build linux
    - run: flutter build apk
    - run: flutter build appbundle
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.DOMAIN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-1
        SOURCE_DIR: build/web
      if: github.event_name == 'release'
    - uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      if: github.event_name == 'release'
  windows:
    needs: ubuntu
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        architecture: x64
    - run: flutter pub get
    - run: flutter test
    - run: flutter build windows
  macos:
    needs: ubuntu
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        architecture: x64
    - run: flutter config --enable-macos-desktop
    - run: flutter pub get
    - run: flutter test
    - run: flutter build macos
    - run: flutter build ios --release --no-codesign
